[package]
name = "bevy_anvil"
version = "0.1.0"
edition = "2024"

[dependencies]
anvil = { git = "https://github.com/paramatrix-dev/anvil/", rev = "4c70b77268503bffb53d6bd95aed46cc4800dc1a", version = "0.1.0" }
bevy = "0.16.1"

[dev-dependencies]
bevy_simple_subsecond_system = "0.1.11"
