[package]
name = "anvil_dylib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
anvil = { git = "https://github.com/gmorenz/anvil/", rev = "a46dcf73c26058df282caa43d0f82e997059a2a1" }
